version: '3.8'
services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DDB_ENDPOINT: http://host.docker.internal:9000
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
