version: '3.8'
services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DDB_ENDPOINT: http://host.docker.internal:9000
      ADMIN_PASSWORD: aloha

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
