version: '3.8'
services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
